### ISSUE TITLE
Iterative pruning example not executing

### ISSUE THREAD

**Issue by piyush-das** [EkdeepSLubana/OrthoReg#2]
Hi,

Although the iterative pruning segment mentions the following command with `pretrained=False`
 `python main.py --model=vgg --pretrained=False --pruning_type=orthoreg --prune_percent=50 --n_rounds=2`

On executing it we get the following error
`FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/iterative/vgg.pth'`

Please let me know if I am missing something.

Thanks

**Comment by EkdeepSLubana** [comment]
Hi!

Just made an update. Since it's been a while, I can't recall why, but there was a conditional statement in the scratch training process. It's highly likely that I included the conditional because I was running some experiments and forgot to remove it. Let me know if there are more issues.

**Comment by piyush-das** [comment]
Thanks, for the update. I'll be sure to let you know if I have any more findings.
