### ISSUE TITLE
[Query] Constraining max VGG pruning does not consider relative importance

### ISSUE THREAD

**Issue by piyush-das** [EkdeepSLubana/OrthoReg#4]
Hi,

It seems that while pruning inorder to constrain pruning on VGG network we are assigning a high value of importance i.e 1e7 to the last few filters based on the 0.05% constraint. However, should we not rather give this high importance values to those filters within the layer which were already having high relative importance, rather than arbitrary assignment of high importance to the last few fitlers as is in case in this [code snippet](https://github.com/EkdeepSLubana/OrthoReg/blob/869f04969dcbd827d25c48246774d243bef355db/pruner.py#L22). In such cases it might so happen that one of the least importance filters get assigned a high importance due to the above constraints. Please correct me if my understanding is flawed.

Thanks

**Comment by EkdeepSLubana** [comment]
IIRC, that list is already sorted and hence we constrain only the last 5% filters. That said, in case I missed on that by mistake, feel free to change that part. I agree with your assessment.
